// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://giscwfqhvjexyiegcfzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdpc2N3ZnFodmpleHlpZWdjZnpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NjI4NDYsImV4cCI6MjA3MDAzODg0Nn0.w4x-Oc7hFNN3UDj6tfIeoTzGdTorKPAgsr1Z4ovhCco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});